// Code generated by "esc -pkg qgraph -prefix  -ignore  -include  -o resources.go manifests"; DO NOT EDIT.

package qgraph

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return []os.FileInfo(fis[0:limit]), nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/manifests/error.yml": {
		name:    "error.yml",
		local:   "manifests/error.yml",
		size:    13,
		modtime: 1543154304,
		compressed: `
H4sIAAAAAAAC/9JVyEvMTbVSSC0qyi8CBAAA///rGPd6DQAAAA==
`,
	},

	"/manifests/kubernetes.yml": {
		name:    "kubernetes.yml",
		local:   "manifests/kubernetes.yml",
		size:    170,
		modtime: 1543154304,
		compressed: `
H4sIAAAAAAAC/0TOSw6CUAyF4TmrOOkcF9ANuAxSsSSNcME+TNi9EV/T5u+X06PJooxbXdSbpkYH3Esj
bW3BHQD0eIgP744mazIP4mmTjElHAGzqYZHakpFe+jlfNUa37WUx6FwagX0tx6Hgq8CC6fcySc3JoP+k
077M9AwAAP//Ek3vvaoAAAA=
`,
	},

	"/manifests/main.yml": {
		name:    "main.yml",
		local:   "manifests/main.yml",
		size:    1905,
		modtime: 1543155278,
		compressed: `
H4sIAAAAAAAC/5xUwW7jOgy85ysI9ZBLmw8wUBQPePdeChR7MliLttU4kpai0s3fL6Q4jl07Rro3wyJn
RsOhnsDigQpg52QD8DtSEONsKDYAAE9wRC7PFagPxubvfATgiYMJQlYKEI6X35pCxcYnlALUf6krc4Cr
4eQigybfudOBrLyooafG2EkBat/FQKxm7J2rMEH+hPu9NVULTI1xFrRL7PCFVkBcLwLELWggDBLDXANT
cJErKht20f/YivcWZcCAjHE2ZiTtZc66N1avXC8dJ2uRxdRYSViAA6jQaqNRqB/shaSLVICxNWMQjpVE
puH8O9+bG40OpKVvjeEROrNPiuMHsSWhsNvt1JwPve/MZJwrZOfMjFrgy0gLldN04fOtf4RPPGJPJ4w2
mEmMz1YuXrRyVpueNZv5/AzbaeVWTWDm+hcxRmVbtdksd9/U2qFtIjZ0bRz+rK6p8uw+qZKyz2oyqvQo
rbqRVXiAt9f/XwG1hhC9dyxQO84DFiaCwYYUs/T3iGzwo6Owu5FLYtqGXNqHPYkY9r8XuBD1QXtjpGQ6
mmCcVf+y8ufW5aVf2PgDBll6ddTF8zJNVd2xhpcGQKbMHYOxzX176Ft/cx9+jZzL2Bk3tQyUOfsP4Jlq
8+funF1JxyGe3Dun2bd+nOLZKq1FMheXcvJ0j4VT6LUBrrp5fYXueGRwVA5VF1Mc1t+SGfzYvuuFs3fX
2q36GwAA//+lPRG+cQcAAA==
`,
	},

	"/manifests/php.yml": {
		name:    "php.yml",
		local:   "manifests/php.yml",
		size:    1131,
		modtime: 1543154304,
		compressed: `
H4sIAAAAAAAC/8ySwW6rMBBF9/mKKy+yy1Nel1bbbX+ge2SRobFkGzozrsrfV4QAgdKq2cEOae6Zo7k+
ILlIFs252QHvmUR9ncTuAOCAD8dFP2DKOpWZmZIWWYjNZQLQtiELn/T6fyIp2TcdxcK8nglTEENQ2SXx
s039FokuhKKX6b6yTid/ZS0E8PiE/8ejmeUjnXyOfwQ8d3ns91gnL9DB8RvdQ/4J/fANHd2nj3do94Td
2tF+a7DyyYXCsfrKlToU2BCLF6WkFsqZVnt8ySSCts6MCwUDBV6sGSOVy0EtzGj0r43hxnRWzzZUJ6WF
623f21AdjZZXnT2fjZx1cuptga8AAAD//0VGz3BrBAAA
`,
	},

	"/manifests": {
		name:  "manifests",
		local: `manifests`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"manifests": {
		_escData["/manifests/error.yml"],
		_escData["/manifests/kubernetes.yml"],
		_escData["/manifests/main.yml"],
		_escData["/manifests/php.yml"],
	},
}
