// Code generated by "esc -pkg qgraph -prefix  -ignore  -include  -o resources.go manifests"; DO NOT EDIT.

package qgraph

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return []os.FileInfo(fis[0:limit]), nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/manifests/error.yml": {
		name:    "error.yml",
		local:   "manifests/error.yml",
		size:    13,
		modtime: 1543299825,
		compressed: `
H4sIAAAAAAAC/9JVyEvMTbVSSC0qyi8CBAAA///rGPd6DQAAAA==
`,
	},

	"/manifests/java.yml": {
		name:    "java.yml",
		local:   "manifests/java.yml",
		size:    846,
		modtime: 1545982580,
		compressed: `
H4sIAAAAAAAC/8yRPW7DMAxG9wC5A6ElU3IAA0HHHqHoZBAy3SqVJZekEvj2hWP5J6lToFtGQeTj+8g9
BGyogBOecbsB+E4k6mKQon8B7OGMXA41pmZs6BL5ywyfABWJZdf2HQWYt09UmIqgiwmQCZK48PEy9VgM
latQaZwxzvGJCtDYWNT5437Ge0wMLccTWZ3pue1gVogX56vad/9G5r5F1hqT16WiMgZxt/ua91neZrEx
VC6PnJd0PMJuqNuZFcSd/GNGLuwh280Di7+P6wL6ElldjVan1C2xOFEKfXBOtH7510Qi/cEZrhwYOeCk
MAt7UQxa5ssYadD7LHjoGv9bfpH/Se2z4VX/JwAA//9fHa6CTgMAAA==
`,
	},

	"/manifests/jenkins.yml": {
		name:    "jenkins.yml",
		local:   "manifests/jenkins.yml",
		size:    509,
		modtime: 1543687698,
		compressed: `
H4sIAAAAAAAC/3SQy2ozMQyF9/MUB2+ySh7AkNX/Qx/DCI9C3XrkqSUX5u3L3AimjdbnovNdITSxxwfL
ZxIdgK/GaqmI+gEArvimGnaRO1Rh5DmXZWKxYMvMblMCI2usaV7dHu7feynKWEqreBqwGvzpiCRjGsn4
aDsbc2MPnSjn8PzsvL7m/xYN2uWIualxRXmcm25rmVUSTd2ufdNfJbHImI74F5Nxv+PSeS9uGF6Fdkw7
oo8klANVSw+KtmOZuWpSYzEPq42H36PfGqvuaLcEnAlIesCNRdRILBw0XffUbZmy+wkAAP//U+4u1/0B
AAA=
`,
	},

	"/manifests/jmeter.yml": {
		name:    "jmeter.yml",
		local:   "manifests/jmeter.yml",
		size:    500,
		modtime: 1543551514,
		compressed: `
H4sIAAAAAAAC/3SQTWrDMBCF9z7FQ5uskgMIsmqhxxCDPKYqsuRqRgXfvtiS25ims34/874rEs1s8TGz
chmAz8qiISexAwBc8UXFNY1pIjfyEvM6c1Kn68JmFwIjiy9h2cwW5uU9Z2GsuRb8GrAZ7OHwlMYwknIv
OwpjZQuZKUb389dx55bXPRnU1PCxinJBnvqg21alhZKE06g26EmFz2kMPfz5XNzvuDw6L2YY/kk8wTyh
nEKi6KhomMhrA7JwkSDKSS20VB7+7n2rLNKg7gk4EhCkY/U5iVJS1zmax59u6xzNdwAAAP//9mwI7PQB
AAA=
`,
	},

	"/manifests/kubernetes.yml": {
		name:    "kubernetes.yml",
		local:   "manifests/kubernetes.yml",
		size:    561,
		modtime: 1543551514,
		compressed: `
H4sIAAAAAAAC/4SRS27zMAyE9z7FQJuskgMIyOr/gR5DYC2mFSpTrkgV8O0Lv5AYfWnNmU8zc4bQwB5v
7ZmrsLF2wHtjtVREfQcAZ3xQDeudux+GyGMu08BiwaaR3XIMRNa+pnE28HD/XktRxlRaxV2AWeB3RU8S
UyTjDbhDc2MPTfKSOUiJHA6/3N+R939hgDadFcEsRbk9ZLzMZKskmg4514y/EvsiMW2sn7vA9YrT9z4n
13V/kg4LHPq/JaEcqFq6UW9rgyNXTWos5mG1cfe1lqfGqusKiwN2ByTdduiLqJFY2Ip3OlDOD/+6TEN2
nwEAAP//zZXusjECAAA=
`,
	},

	"/manifests/load_test.yml": {
		name:    "load_test.yml",
		local:   "manifests/load_test.yml",
		size:    411,
		modtime: 1543467504,
		compressed: `
H4sIAAAAAAAC/6TQsU7EMBAE0D5fMbom1V16/wiltcR7iiHxmvUaC74eGSsnIURFa814n+aKRAc77ELB
GxebgLfKxaKk4iYAuOKd1I/Yy8HG6h9pzylkicn8WUoUlb97QGYtsRgnczCt53PgsmrMPe1wedrI5oIP
qYrzN5jgmdEvcLg8anequznMm1l2y9Jau9FnVb6tcsx/WZWzqPldVtp96OZ/UFkZQToWjYYzSEt9D9g2
xBgXf7MXO3JnmlIq8cfCQ0xq8U6r+deYwvQVAAD//wUJAPabAQAA
`,
	},

	"/manifests/main.yml": {
		name:    "main.yml",
		local:   "manifests/main.yml",
		size:    3601,
		modtime: 1545982433,
		compressed: `
H4sIAAAAAAAC/5xWQW/rNgy+F+h/ILxDLi/pMOwwBHgYBhS7vkuBYSeDtZlYtSJpEpUi/36QbMd2LOsl
vbUK+fHTx4+Ut6DwRHuwWvPzE8B/nhwLrdw+/AewhTPasovB+iRU/Lv7DcCQdcIxKd4DW389r8lVVpgA
tIfinwa5S47FoNZw0R4+UTEctA3/WKjJSH05keI/ixHmgF7yHopWeke2WHKSusJQ5lFGomrA0lFoNaPD
uicCrFM8CB17l+BhyWlvKyqPVnvzVZEGFIgoC7WSynglvdoaqz+o4u2AkOKIyol3SWWjHZctXcqqoaoV
6vgY09eJXo6tqBicayCgQksXGFBHthWqWtTINLhqYCY97aFA1xbj+W25v1w7ugSNsfqMEj4bip1LVt4V
qTJKZ6q8alCaA2IGbVT9ijXV9+NETLaUGuuSyXFJCt8l1V+XFyGAQQADPDBZ4IaSo5KXePNmPW3Wb/+m
oeM61nO7XVLGzd8o3U+wXCvMCtIoYcSJ52yDM+dbZ5juXsrrNbWqRV9oTW74/r2/cDFHQ8vigBWXrVD1
w4jdvYvnp+enVcDc9pwWTW2j8DvowxXUpSc/32ihDhYdW1+xt5Rt0uiiaKp5pvsGUrSBtX8nq4hpzQ9o
jBTzHZwpd53iIQc+BTdQ6ZqGiqYx3+ADz5i0zU25deuklZh2OwoeOjsPXbhmecEkyiTuxiX3Upaojh6P
NE0ez/LuKvoHoOyfoaBoaZCbYm37wC/w9uP1B2Bdg/PGaNu9xsEMbIngqkhwZTg9oxVhHtxuzcdkaeNi
bP+OBRohPba9p5h6xRpm4/YvL0fBjX/fVfr00nq1lV69/Pbr739EOxwFF5mLHwWXls7CCa2Kr30OdMnp
D4IU6xM6Tn6VFEPb4mYo7hn7IQPQUizv3QNvqGnM+vT9OxE/wkfokHOtmhztoPrDqCEpAXsVbQBdH4PJ
XaaDNpM0TpxpzO2wTinnk0PkfE6XGyM7cDG85Iuhu/o7R88a7CetlihUeT7ds221IghdkQTnU7dqw1GN
jFAL1ybbPq78e0rgJB4q6cNEpN0UH9f7ILvYPBypVqg7KfbBc8CMA28knjppbHvnwT701ohLETMgY/DC
zzPRMhBd4CJ9LlIuv4vcFP8HAAD//30HbcERDgAA
`,
	},

	"/manifests/php.yml": {
		name:    "php.yml",
		local:   "manifests/php.yml",
		size:    1159,
		modtime: 1543551514,
		compressed: `
H4sIAAAAAAAC/8ySsU7DQAyG9z7FrwzdigrjCVh5AfbolLrU0t0l2L6Kvj1K0zRNCIhuyRbJ/+dP/m+D
5CM5NIdmBXxmUuM6qVsBwAZHL2U3UFR1qrIIJSuzkhTnCcBODTlwssv/jrQSblqKQ/F+IAxB9EETn5RH
m7otGn0IZSfTflWddnxhTQTw/ILH7bYY5SPtOMd/Al7bPNZrzJMn6ODlg+4h/4Z++oGO/ovjHdodYTV3
tL8a3HPyofRivPeV9QU2JMpqlMzBJNNsj2+ZVHGqs+BMQU8BqysGaTWfrDz6kNuFV7GHUww3wqOWFmU8
mE2Ub9tflPFVbHrj0Zta1pEHtU4a+A4AAP//QbLR9YcEAAA=
`,
	},

	"/manifests/plain_vm.yml": {
		name:    "plain_vm.yml",
		local:   "manifests/plain_vm.yml",
		size:    165,
		modtime: 1543551514,
		compressed: `
H4sIAAAAAAAC/zTOwanEMAwE0HuqGHzPL8AN/DKMyCogcGSvJBvS/ZKEXIfhzaxQOjijVxIt81iA72AP
aep5AVZMsvJ00i5KtZCF7LRFWgCgs7l4sEZG2OA7/LBvJv1SMtL/YHecbRhuAa8A8fwoW1MP0iiT6rim
3j9/51HTLwAA//92kVu5pQAAAA==
`,
	},

	"/manifests": {
		name:  "manifests",
		local: `manifests`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"manifests": {
		_escData["/manifests/error.yml"],
		_escData["/manifests/java.yml"],
		_escData["/manifests/jenkins.yml"],
		_escData["/manifests/jmeter.yml"],
		_escData["/manifests/kubernetes.yml"],
		_escData["/manifests/load_test.yml"],
		_escData["/manifests/main.yml"],
		_escData["/manifests/php.yml"],
		_escData["/manifests/plain_vm.yml"],
	},
}
