---
schema: v0.1

env_name: kunlun
resource_group_name: ((resource_group_name))
location: ((location))

iaas: azure # this can be azure or some other platform

vm_groups:
  - name: jumpbox
    meta:
      group_type: jumpbox
    count: 1
    sku: Standard_DS1_v2
    type: vm # this can be vm or vmss, currently only vm is supported
    os_profile:
      admin_name: ((admin_name))
      linux_configuration:
        ssh:
          public_keys:
            - ((admin_ssh.public_key))
    storage:
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
      os_disk:
        managed_disk_type: Standard_LRS
        caching: ReadWrite
        create_option: FromImage
    networks:
      - subnet_name: snet-1
        network_security_group_name: ssh_nsg
        public_ip: static

  - name: jenkins-master
    count: 1
    sku: Standard_DS1_v2
    type: vm
    os_profile:
      admin_name: ((admin_name))
      linux_configuration:
        ssh:
          public_keys:
            - ((admin_ssh.public_key))
    storage:
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
      os_disk:
        managed_disk_type: Standard_LRS
        caching: ReadWrite
        create_option: FromImage
      data_disks:
        - managed_disk_type: Standard_LRS
          caching: ReadWrite
          create_option: Empty
          disk_size_gb: 40
    networks:
      - subnet_name: snet-1
        network_security_group_name: jenkins_nsg  
        public_ip: static
    roles:
      - name: kunlun.datadisk
      - name: kunlun.jenkins
        vars:
          kunlun_jenkins_admin_username: "jenkins"
          kunlun_jenkins_admin_password: "((kunlun_jenkins_admin_password))"

vnets:
  - name: vnet-1
    address_space: 10.0.0.0/16
    subnets:
      - name: snet-1
        range: 10.0.0.0/24
        gateway: 10.0.0.1    

load_balancers:

network_security_groups:
  - name: ssh_nsg
    network_security_rules:
      - name: allow-ssh
        priority: 100
        direction: Inbound
        access: Allow
        protocol: Tcp
        source_port_range: "*"
        destination_port_range: 22
        source_address_prefix: "*"
        destination_address_prefix: "*"
  - name: jenkins_nsg
    network_security_rules:
      - name: allow-http
        priority: 200
        direction: Inbound
        access: Allow
        protocol: Tcp
        source_port_range: "*"
        destination_port_range: 80
        source_address_prefix: "*"
        destination_address_prefix: "*"
      - name: allow-ssh-dev
        priority: 1001
        direction: Inbound
        access: Allow
        protocol: Tcp
        source_port_range: "*"
        destination_port_range: 22
        source_address_prefix: "*"
        destination_address_prefix: "*"

variables:
  - name: admin_ssh
    type: ssh
  - name: kunlun_jenkins_admin_password
    type: password
