// Code generated by "esc -pkg builtinmanifests -prefix  -ignore  -include  -o resources.go manifests"; DO NOT EDIT.

package builtinmanifests

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return []os.FileInfo(fis[0:limit]), nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/manifests/large_php.yml": {
		name:    "large_php.yml",
		local:   "manifests/large_php.yml",
		size:    3838,
		modtime: 1543468833,
		compressed: `
H4sIAAAAAAAC/+xWTYvkOA++51eI7svUS1V1VzMML7kt+8EODCxM97CHZQmOo0o87dhZS051za9f7LiS
1Ef3fLCHXRgamrIkS/KjR4pWq1VGssFW5NDfrjdZhqYvjGgxh0dvtDeZQ7LeSSxqZ32XdK9eXRAvFpm2
UrCyJlgcfi8WWaaEoBzEJ+8QroEbRSCFgRKTzDog2yJYbtBBpwVvrWuzrG8H/5RnACsYgn/0bVfapwwA
oEUWefwFMGTC++7ERlpvOIdNPNCjz+GehamEq4qf7jdFfxcVw72+Pcmvb0NyfUu0BOmdQ8N6D9bofVAp
AvJdZx1jFb1YKjpnt0rjIStRtcqMsE2nxSIZaGX8UyGt2arauwG+pAIgaqYDQOdLrWTxiHuaiwM2B99E
zXoyS1GIrRP1mJNqZwcAu92iy+FD6Q37e3Q9uuwoIjVB/6Mw1igp9JRdAHPzZn37evXu4X4U9+gokkAL
RuIkt1RUih6nsK0wosYqSlPZxsK8ez+5k0I2ytQ5vEdR/e4U46RyKBgL2w2k+8XZ9m14WzKoBIvofobW
6ovjvhj5LPbPbcf7mTp6J/UJi7rMYXN7O+quE5NDzXs0A1Teq2pGvRKj5CZyeglqG49LsGZQwM56XQWC
1gadYKxAUPQawxjknXXTs1dAvjTIiYdkkFebMaFkXRBK7xTvj1qdqCkM1dkJBVWXA7FgJaPGWY2zaPMJ
sg5VCGhksx7eYbmiyDT6hh793mrfW+2/2WraiqoohRZGoksmx7LnbEshH9FUhagqh0RFZ61ODi6qvrC9
d1gOfTg2+dDKB4AUgSesgC3UOLwfuEGosNN236JhIOlUx/SZ5r+sjV6GTULaaqp5L9xR23XOfkTJRVo6
gm3RCW5Coz+nG9t+7qBWXDjsFaUt5ZJ8vHiSbdd0WdYb5KN1pJ8qfCgAdUJiYOI6/t1s3gyjIRLjbEye
UMQJU88v370eVbVg3In9qNxk2RFJjvK6RKujyRoll7hzluELBGtQaG7CJC7PPwANczeoslkd2Eqrc3iQ
HVzD0NNCQy+0D7z740F2S/iVOf2nP6e71nEO/5+3t8O/PBInLlzdXCWZcliFVj6Ei5sacqBxcBp2uuh8
Db+FlXOnCJegOJgZyyC0tjus1qeVoual55wkejd8tJzXzyATNF8LzIeqW8IPWk+obJ01HKpzBs+hbM8q
vn6WzMtdnBU5uzxqjmh5PnDOLl1ELJZkFYLNIFM2XMjhbjbzK+VQDh+Kt6a03lSjSkiJRHnAz+4+U8M0
TQJ2RWrJq/9dTVGQWJm4QhzZzFBOHkYkHW7V0/NeLtvNqfctgBE1F/Da/GvwSk3yD+GV9cIpUSY0RiQO
29psiQynvwMAAP//FAGNRf4OAAA=
`,
	},

	"/manifests/maximum_php.yml": {
		name:    "maximum_php.yml",
		local:   "manifests/maximum_php.yml",
		size:    3838,
		modtime: 1543468833,
		compressed: `
H4sIAAAAAAAC/+xWTYvkOA++51eI7svUS1V1VzMML7kt+8EODCxM97CHZQmOo0o87dhZS051za9f7LiS
1Ef3fLCHXRgamrIkS/KjR4pWq1VGssFW5NDfrjdZhqYvjGgxh0dvtDeZQ7LeSSxqZ32XdK9eXRAvFpm2
UrCyJlgcfi8WWaaEoBzEJ+8QroEbRSCFgRKTzDog2yJYbtBBpwVvrWuzrG8H/5RnACsYgn/0bVfapwwA
oEUWefwFMGTC++7ERlpvOIdNPNCjz+GehamEq4qf7jdFfxcVw72+Pcmvb0NyfUu0BOmdQ8N6D9bofVAp
AvJdZx1jFb1YKjpnt0rjIStRtcqMsE2nxSIZaGX8UyGt2arauwG+pAIgaqYDQOdLrWTxiHuaiwM2B99E
zXoyS1GIrRP1mJNqZwcAu92iy+FD6Q37e3Q9uuwoIjVB/6Mw1igp9JRdAHPzZn37evXu4X4U9+gokkAL
RuIkt1RUih6nsK0wosYqSlPZxsK8ez+5k0I2ytQ5vEdR/e4U46RyKBgL2w2k+8XZ9m14WzKoBIvofobW
6ovjvhj5LPbPbcf7mTp6J/UJi7rMYXN7O+quE5NDzXs0A1Teq2pGvRKj5CZyeglqG49LsGZQwM56XQWC
1gadYKxAUPQawxjknXXTs1dAvjTIiYdkkFebMaFkXRBK7xTvj1qdqCkM1dkJBVWXA7FgJaPGWY2zaPMJ
sg5VCGhksx7eYbmiyDT6hh793mrfW+2/2WraiqoohRZGoksmx7LnbEshH9FUhagqh0RFZ61ODi6qvrC9
d1gOfTg2+dDKB4AUgSesgC3UOLwfuEGosNN236JhIOlUx/SZ5r+sjV6GTULaaqp5L9xR23XOfkTJRVo6
gm3RCW5Coz+nG9t+7qBWXDjsFaUt5ZJ8vHiSbdd0WdYb5KN1pJ8qfCgAdUJiYOI6/t1s3gyjIRLjbEye
UMQJU88v370eVbVg3In9qNxk2RFJjvK6RKujyRoll7hzluELBGtQaG7CJC7PPwANczeoslkd2Eqrc3iQ
HVzD0NNCQy+0D7z740F2S/iVOf2nP6e71nEO/5+3t8O/PBInLlzdXCWZcliFVj6Ei5sacqBxcBp2uuh8
Db+FlXOnCJegOJgZyyC0tjus1qeVoual55wkejd8tJzXzyATNF8LzIeqW8IPWk+obJ01HKpzBs+hbM8q
vn6WzMtdnBU5uzxqjmh5PnDOLl1ELJZkFYLNIFM2XMjhbjbzK+VQDh+Kt6a03lSjSkiJRHnAz+4+U8M0
TQJ2RWrJq/9dTVGQWJm4QhzZzFBOHkYkHW7V0/NeLtvNqfctgBE1F/Da/GvwSk3yD+GV9cIpUSY0RiQO
29psiQynvwMAAP//FAGNRf4OAAA=
`,
	},

	"/manifests/medium_php.yml": {
		name:    "medium_php.yml",
		local:   "manifests/medium_php.yml",
		size:    3838,
		modtime: 1543468833,
		compressed: `
H4sIAAAAAAAC/+xWTYvkOA++51eI7svUS1V1VzMML7kt+8EODCxM97CHZQmOo0o87dhZS051za9f7LiS
1Ef3fLCHXRgamrIkS/KjR4pWq1VGssFW5NDfrjdZhqYvjGgxh0dvtDeZQ7LeSSxqZ32XdK9eXRAvFpm2
UrCyJlgcfi8WWaaEoBzEJ+8QroEbRSCFgRKTzDog2yJYbtBBpwVvrWuzrG8H/5RnACsYgn/0bVfapwwA
oEUWefwFMGTC++7ERlpvOIdNPNCjz+GehamEq4qf7jdFfxcVw72+Pcmvb0NyfUu0BOmdQ8N6D9bofVAp
AvJdZx1jFb1YKjpnt0rjIStRtcqMsE2nxSIZaGX8UyGt2arauwG+pAIgaqYDQOdLrWTxiHuaiwM2B99E
zXoyS1GIrRP1mJNqZwcAu92iy+FD6Q37e3Q9uuwoIjVB/6Mw1igp9JRdAHPzZn37evXu4X4U9+gokkAL
RuIkt1RUih6nsK0wosYqSlPZxsK8ez+5k0I2ytQ5vEdR/e4U46RyKBgL2w2k+8XZ9m14WzKoBIvofobW
6ovjvhj5LPbPbcf7mTp6J/UJi7rMYXN7O+quE5NDzXs0A1Teq2pGvRKj5CZyeglqG49LsGZQwM56XQWC
1gadYKxAUPQawxjknXXTs1dAvjTIiYdkkFebMaFkXRBK7xTvj1qdqCkM1dkJBVWXA7FgJaPGWY2zaPMJ
sg5VCGhksx7eYbmiyDT6hh793mrfW+2/2WraiqoohRZGoksmx7LnbEshH9FUhagqh0RFZ61ODi6qvrC9
d1gOfTg2+dDKB4AUgSesgC3UOLwfuEGosNN236JhIOlUx/SZ5r+sjV6GTULaaqp5L9xR23XOfkTJRVo6
gm3RCW5Coz+nG9t+7qBWXDjsFaUt5ZJ8vHiSbdd0WdYb5KN1pJ8qfCgAdUJiYOI6/t1s3gyjIRLjbEye
UMQJU88v370eVbVg3In9qNxk2RFJjvK6RKujyRoll7hzluELBGtQaG7CJC7PPwANczeoslkd2Eqrc3iQ
HVzD0NNCQy+0D7z740F2S/iVOf2nP6e71nEO/5+3t8O/PBInLlzdXCWZcliFVj6Ei5sacqBxcBp2uuh8
Db+FlXOnCJegOJgZyyC0tjus1qeVoual55wkejd8tJzXzyATNF8LzIeqW8IPWk+obJ01HKpzBs+hbM8q
vn6WzMtdnBU5uzxqjmh5PnDOLl1ELJZkFYLNIFM2XMjhbjbzK+VQDh+Kt6a03lSjSkiJRHnAz+4+U8M0
TQJ2RWrJq/9dTVGQWJm4QhzZzFBOHkYkHW7V0/NeLtvNqfctgBE1F/Da/GvwSk3yD+GV9cIpUSY0RiQO
29psiQynvwMAAP//FAGNRf4OAAA=
`,
	},

	"/manifests/small_jmeter.yml": {
		name:    "small_jmeter.yml",
		local:   "manifests/small_jmeter.yml",
		size:    3305,
		modtime: 1543468838,
		compressed: `
H4sIAAAAAAAC/+xWT2/cthO981MM8jsk+0PlrhZ2gOhW9A8QIKc4RY/ELDUrsaZIgUPK3nz6gpJWf9a7
rhH0UBSBL0u+0Zvxm3kjZVkmWNXUYAHd9iYXgmwnLTZUwEO0JlrhiV30imTlXWxH7N27C9ebjTBOYdDO
pojT781GCI3IBeDX6An+B6HWDAot7Gm8cx7YNQQu1OShNRgOzjdCdM3Az4UAyGBI/mds2r17EgAADQUs
+l8AQyXh2J7FKBdtKCDvD/wQC7gPaEv0pfzlPpfdrgeG57rmrL6uScV1DfMPoKL3ZIM5grPmmCDNwLFt
nQ9U9iyOZevdQRs6VYVlo+0k23zabMYAo218ksrZg66iH+QbIQDmej4AtHFvtJIPdOTlddLmxM1c38xh
YxYOzmM11aSbxQHAHQ7kC/h9H22I9+Q78mKVkeuE/4zWWa3QzNUlMfP3N9vb7NOX++m6I8/9EBgMxGG8
dyxLzQ9z2gYtVlT2t2PbpsZ8+jzTKVS1tlUBnwnLP7wONEOeMJB07TB0v3nXfEz/2xhQYsCefqFW9uq8
L2Z+lvvXpg3HBdyzs/5KstoXkG+3PWYpPDo/15MBx72lMA4IWwpZPrGM0ZJJRa/DceVB5lparsTZbOi2
AA4YtOoR7wwtsi2tfZPkSWWKpbkaCuSzlJY8f4N/vtvguw2u2uD29S5YSPY3RhhGNnkB4Lob4PV2uIgO
Webmol/N3liEcVjKVLoki3tDZZr2a9g0+xcJGldSAW9Z28qQtK6kty+Fh9oTlrJNSvRPnlbOlXjjXCtH
a+/uXor02LQytolau7KAnRCisxRWL+Vu3lxYlp6YJbeo+jpu+r8f8/eDCftWP2vC2erzaKvlw7vbCaow
0CMeJzC/xLQanyXZ7u7uJboE5ydIiF6FPRq0ilLDxeVJXEmxXMzPwn28MIBojHvMmOt5fL12KX7dxlJ7
UoPPPtq9i7acIFSKmAv4KVEtaFxwypkCvqh23lfDl1v6bJGjNG/+/2bOQhy07TfwKma3O2c4dbr1dNBP
11kux61fOd8qWVZSd1m2/D+q23MZznbTSoXdv0SFfPvhwz+pg+jQ67RGV96bXv6Lb5J0+isAAP//9o5A
JekMAAA=
`,
	},

	"/manifests/small_kubernetes.yml": {
		name:    "small_kubernetes.yml",
		local:   "manifests/small_kubernetes.yml",
		size:    3924,
		modtime: 1543468833,
		compressed: `
H4sIAAAAAAAC/+xWW6vbuBN/96cYTl56/iRpEkopfvuzF7ZQWOhp2YdlMbI8sdUjS17NyGn66RfJiu1c
Ti/LPuxCOXCI5jeaGf/molmtVhnJBluRQ79Zb7MMTV8Y0WIOj95obzKHZL2TWNTO+i5hz57dEN/fZ9pK
wcqaoHH6fX+fZUoIykF88g5hAdwoAikMlJhk1gHZFsFygw46LXhvXZtlfTvYpzwDWMHg/INvu9J+zAAA
WmSRx18AQyR87C50pPWGc9jGAz36HB5YmEq4qvjxYVv0uwgM9/r2Ir6+DcH1LdESpHcODesjWKOPAVIE
5LvOOsYqWrFUdM7ulcZTVKJqlRlpm07390lBK+M/FtKavaq9G+hLEABRMx0AOl9qJYtHPNJcHLg52SZq
1pNa8kJsnajHmFQ7OwDY/R5dDu9Lb9g/oOvRZWceqQn4D8JYo6TQU3SBzO3L9ebF6s27h1Hco6NYBFow
Eie5paJS9Di5bYURNVZRmtI2JubN28mcFLJRps7hLYrqN6cYJ8ihYCxsNxTdz862r8O3JYVKsIjmZ2yt
vtrvZz1f+f6p7fg4g6N1Up+wqMsctpvNiC1SJYec92gGqrxX1az0SoyS57Gml6D28bgEawYADtbrKhRo
bdAJxgoERavRjUE+WDd99grIlwY51SEZ5NV2DChpF4TSO8XHs1YnagpDdXZRgqrLgViwkhFxVuPM23yC
rEMWAhtZNodKdAYZ6csturtq0e+t9r3V/puttgBtRVWUQgsj0SWlc9nT2qWQj2iqQlSVQ6Kis1YnEzeh
r2zxqRnHTh/6+cSSIvCEFbCFGgcSgBuECjttjy0aBpJOdUxfmAA30YtZMGVtuh/9DAuHtBWOegC9cCP1
i6GNnP2Akou0nwT9ohPchJnwFDZOiHMTteLCYa8orTS35LOrF1F3TZdlvUE+2176qSBOuaJOSAyFu45/
z7cvh0kS6+hqql5UlBOmnl/evRihWjAexHEEt1l2Vk/R9BT2dRUuLqdxkt0qtmRsHumTNRnUGhSamzDC
S7xxt2HuBnCEYl7YSqtzeCc7WMAwEISGXmgf6vX3d7Jbwi/M6T/9Mb9tHefwajMTLcDhnx6JU4XcPb9L
MuWwCrPg5DKuesihBYLhsBRGB2v4NeysB0W4BMVBzVgGobU9YLW++q7wnH72s64C3u2SyHn9JFMB+3ai
3lfdEv6v9ZylvbOGQ9Zu0HVK6GegbxlNp7vzUiiu0p/dnl1nTXVjgl3dGumbkxfztArepmfYKRsu5LCb
vSSVciiH5+e1Ka031QgJKZEoD0Taw8zMeVLTMz4MnkBgkTr37n93kxckViYuJmc6rzaXFkYyHe7Vx6et
3NabV+PfIYyoucHX9l/D1273T/KV9cIpUSY2RiZOO+BsNw2nvwIAAP//Ps/0l1QPAAA=
`,
	},

	"/manifests/small_php.yml": {
		name:    "small_php.yml",
		local:   "manifests/small_php.yml",
		size:    5561,
		modtime: 1543468833,
		compressed: `
H4sIAAAAAAAC/+xXTY/bOA+++1cQ00M7LybpOGiLt77tJ7ZAgQU6LfawWBiyxdjqyJJWlJymv34h2fFH
4qQf6KG7GAwwiEWKpB/yIenVapVQWWPDMmhv12mSoGpzxRrM4N4r6VVikbS3JeaV1d70sidPFo6vrxOp
S+aEVkHj8Pv6OkkEY5QB++gtwiNwtSAomYIC+zNtgXSDoF2NFoxkbqttkyRt09mnLAFYQef8vW9MoT8k
AAANOpbFXwBdJG5vjnRK7ZXLII0PdO8zuHNMcWZ5/vNdmrebKOjutc1RfG0TgmsbohsovbWonNyDVnIf
RIKAvDHaOuTRiqbcWL0VEg9RMd4INcA2Pl1f9wpSKP8hL7XaisrbDr5eBEBUjw8AxhdSlPk97ml6HLA5
2Caq16Na74WctqwaYhLN5AFAb7doM3hXeOX8HdoWbTLzSHWQ/8SUVqJkcowugJm+WN8+W71+ezcct2gp
FoFkDsn155pyLuh+dNswxSrk8bRP25CY129GcyUra6GqDN4g439Y4XAUWWQOc226ovvV6uZVeLdegTPH
ovkJWqvP9nvR84nvXxrj9hNxtE7iI+ZVkUF6ezvIHvWVHHLeouqg8l7wSekVGE+expq+AbGNjzegVSeA
nfaShwKtFFrmkAOjaDW6Ueh22o6vvQLyhULX1yEpdKt0CKjXzglLb4Xbz6hOVOeKquSoBIXJgBxzoowS
qyVOvE07yDpkIaCRTDi8w2JFsdLoazj6wLUHrv07uSY143nBJFMl2l5lfnZOt2DlPSqeM84tEuVGa9kb
WBR9Jr93WHREHFjecfkAkCDwhBychgq79wdXI3A0Uu8bVA6otMI4+gT7l6XRSrdKlJqPOW+ZndHOWP0e
S5f3W0fQzQ1zdSD6OdlA+6mBSrjcYiuoX1OWzoeLR9Ga2kyb2PsGHdpVwLZn8YU29mNKsx720MIeWtjZ
Fvbs9rNbywSyTzC9K9dvNcwXpZ2LsyTuI4h9LcSdo2KFRB5K/ZxsRuITpUZzzOAxCVVJzJXm+PiSuqst
Mp6bAEO8OZ0VC/pSa5P3pN48v6RpWWNyb4JpoXkGmyRpFbrZh0s7joJDpybDyhjGOv49TV90BIxpPsnB
0SyxTFXTy5tng6hiDndsPwjTJUuz0pka2zx/fslcEKdJMhtPsxddGmizbhhPlqbWyStfGG01Munq0ECL
03KtnTOdKJlMAKdLLTN4Wxp4BB0VmYSWSR8m3p9vS3MDvznX/6e/xrvaugz+P10sLP7tQ+a7KXT19Ko/
ExZ5WCIO7uJHIrowQIPR8DkZja/h9/C1uxOENyBcUFPaAZNS75CvjxNG9aXXOQp00+3L1sszyATJlwLz
jpsb+EHKEZWt1cqF7JzAc0jbWcGXbzHTdOcnSU6WW9+sLE9XnZNLi4jFlKyCswlkQocLGWwmHYQLi2XX
31+pQnvFBxErSyTKAn5694kc9ntMwC7vaXn1v6vRC5ITKk7+mc4E5d7CgKTFrfhw3sqy3rT0vgYwonoB
r/S7wasnyTfH62jOfiFkK47tMmzpfxS3UxiO1ogZCpvvBIX09uXLb4lD0jIrwsYza1nDkj75dghP/wQA
AP//6oRw4bkVAAA=
`,
	},

	"/manifests/small_tomcat.yml": {
		name:    "small_tomcat.yml",
		local:   "manifests/small_tomcat.yml",
		size:    3987,
		modtime: 1543468833,
		compressed: `
H4sIAAAAAAAC/+xWTYvkOA++51eInsvUS1VNVzMML7kt+8EODCxM97CHZQmOrUo87dhZS051za9fnLiS
1FfPB3vYhaGhKUuypDx6JGu1WmUka2xEDt3tepNlaLvCigZzeAzWBJt5JBe8xKLyLrRJ9/LlBfFikRkn
BWtno8Xh92KRZVoIykF8Ch7hBXCtCaSwUGKSOQ/kGgTHNXpojeCt802Wdc3gn/IMYAVD8I+haUv3lAEA
NMgi738BDJnwvj2xkS5YzmHTH+gx5HDPwirhVfHT/abo7nrFcK9rTvLrmphc1xAtQQbv0bLZg7NmH1Wa
gELbOs+oei+Oita7rTZ4yEqoRtsRtum0WCQDo214KqSzW10FP8CXVABE9XQAaENptCwecU9zccTm4Juo
Xk9mKQqx86Iac9LN7ADgtlv0OXwog+Vwj75Dnx1FpDrqfxTWWS2FmbKLYG7erG9fr9493I/iDj31JDCC
kTjJHRVK0+MUthFWVKh6aSrbWJh37yd3Usha2yqH9yjU714zTiqPgrFw7UC6X7xr3sZvSwZKsOjdz9Ba
fXHcZyOfxf65aXk/U/feSX/Coipz2NzejroXicmx5h3aAaoQtJpRr8Re8qrn9BL0tj8uwdlBATsXjIoE
rSx6wahAUO+1D2ORd85Pn70CCqVFTjwki7zajAkl64JQBq95f9TqRHVhqcpOKKjbHIgFa9lrvDM4izaf
IOtYhYhGNuvhHZYr6plG39Kj33vte6/9N3vNOKGKUhhhJfpkciy7ZlsK+YhWFUIpj0RF65xJDi6qvrC/
d1gOjTh2+dDLB4A0QSBUwA4qHL4fuEZQ2Bq3b9AykPS6ZfpM91/W9l6GVUI6NdW8E/6o7VrvPqLkIm0d
0bZoBdex0a/pxrafO6g0Fx47TWlNuSQfL55ky66Rgq/mOFgVg1UxjIhWEO2cVzHUc/q4JXUW+WjT6Sbu
HEpLrZAYOb7u/15t3gxDp6fc2QQ+IZ8Xtppfvns9qirBuBP7UbnJsiP6HeV1ibBHQ7uXXGLlWYbPULdG
YbiOM748f1tq5nZQZbMKs5PO5PAgW3gBw7QQBjphQmT0Hw+yXcKvzOk//TnddZ5z+P98cHj8KyBxYtnN
q5sk0x5VHBKHcP0SiBwbJDqN62LvfA2/xW12pwmXoDmaWccgjHE7VOvTSlH93OecJHo3vIc+mCvIRM3X
AvNBtUv4wZgJla13lmN1zuA5lO2q4uun1LzcxVmRs8tD7IiW56Ps7NJFxPqSrGKwGWTaxQs53M1eE6U9
yuEJemtLF6waVUJKJMojfm73mRqmORWxK1JL3vzvZoqCxNr2y8mRzQzl5GFE0uNWP133ctluTr1vAYyo
voDX5l+DV2qSfwivrBNeizKhMSJx2ANn++lwOn46Lg/92aVR9HcAAAD//6IpSNCTDwAA
`,
	},

	"/manifests/small_wildfly.yml": {
		name:    "small_wildfly.yml",
		local:   "manifests/small_wildfly.yml",
		size:    3843,
		modtime: 1543468833,
		compressed: `
H4sIAAAAAAAC/+xWTYvkOA++51eI7svUS1V1VzMML7kt+8EODCxM97CHZQmOrUo87dhZS051za9fnLiS
1Ef3fLCHXRgamrIkS/KjR4pWq1VGssZG5NDdrjdZhrYrrGgwh8dgTbCZR3LBSywq70KbdK9eXRAvFplx
UrB2Nlocfi8WWaaFoBzEp+ARroFrTSCFhRKTzHkg1yA4rtFDawRvnW+yrGsG/5RnACsYgn8MTVu6pwwA
oEEWef8LYMiE9+2JjXTBcg6b/kCPIYd7FlYJr4qf7jdFd9crhntdc5Jf18TkuoZoCTJ4j5bNHpw1+6jS
BBTa1nlG1XtxVLTebbXBQ1ZCNdqOsE2nxSIZGG3DUyGd3eoq+AG+pAIgqqcDQBtKo2XxiHuaiyM2B99E
9XoyS1GInRfVmJNuZgcAt92iz+FDGSyHe/Qd+uwoItVR/6OwzmopzJRdBHPzZn37evXu4X4Ud+ipJ4ER
jMRJ7qhQmh6nsI2wokLVS1PZxsK8ez+5k0LW2lY5vEehfveacVJ5FIyFawfS/eJd8za+LRkowaJ3P0Nr
9cVxX4x8FvvnpuX9TN17J/0Ji6rMYXN7O+quE5NjzTu0A1QhaDWjXom95Kbn9BL0tj8uwdlBATsXjIoE
rSx6wahAUO+1D2ORd85Pz14BhdIiJx6SRV5txoSSdUEog9e8P2p1orqwVGUnFNRtDsSCtew13hmcRZtP
kHWsQkQjm/XwDssV9Uyjb+nR7732vdf+m71mnFBFKYywEn0yOZY9Z1sK+YhWFUIpj0RF65xJDi6qvrC/
d1gOjTh2+dDLB4A0QSBUwA4qHN4PXCMobI3bN2gZSHrdMn2m+y9rey/DKiGdmmreCX/Udq13H1FykbaO
aFu0guvY6M/pxrafO6g0Fx47TWlNuSQfL55ku9NGbc0+yzqLfLSTdFOVD0WgVkiMbFz3fzebN8N46Mlx
NitPaOKFreaX716Pqkow7sR+VG6y7IgoR3ldotbReO0ll/hzluELJKtRGK7jNC7PvwI1czuoslkt2Eln
cniQLVzD0NfCQCdMiNz740G2S/iVOf2nP6e7znMO/5+3uMe/AhInPlzdXCWZ9qhiOx/C9esacqRydBoX
u975Gn6Le+dOEy5BczSzjkEY43ao1qeVovql55wkejd8uXwwzyATNV8LzAfVLuEHYyZUtt5ZjtU5g+dQ
tmcVXz9P5uUuzoqcXR43R7Q8Hzpnly4i1pdkFYPNINMuXsjhbjb3lfYoh4/FW1u6YNWoElIiUR7xc7vP
1DBNlIhdkVry6n9XUxQk1rZfI45sZignDyOSHrf66Xkvl+3m1PsWwIjqC3ht/jV4pSb5h/DKOuG1KBMa
IxKHjW22ScbT3wEAAP//DPOeZAMPAAA=
`,
	},

	"/manifests": {
		name:  "manifests",
		local: `manifests`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"manifests": {
		_escData["/manifests/large_php.yml"],
		_escData["/manifests/maximum_php.yml"],
		_escData["/manifests/medium_php.yml"],
		_escData["/manifests/small_jmeter.yml"],
		_escData["/manifests/small_kubernetes.yml"],
		_escData["/manifests/small_php.yml"],
		_escData["/manifests/small_tomcat.yml"],
		_escData["/manifests/small_wildfly.yml"],
	},
}
