// Code generated by "esc -pkg builtinmanifests -prefix  -ignore  -include  -o resources.go manifests"; DO NOT EDIT.

package builtinmanifests

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return []os.FileInfo(fis[0:limit]), nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/manifests/large_php.yml": {
		name:    "large_php.yml",
		local:   "manifests/large_php.yml",
		size:    3546,
		modtime: 1543468996,
		compressed: `
H4sIAAAAAAAC/+xWTYvcOBO++1cUk0v6pbszPYTw4tuyH2wgsJBJ2MOyGFmqtpWWJa2q5E7n1y+y3bb7
azYZ9pDDMjC06imVyk89VdJqtcpI1tiIHNr79SbL0LaFFQ3msIvWRJsFJBeDxKIKLvoBe/nyinmxyIyT
grWzyeP4e7HIMi0E5SC+xIDwArjWBFJYKHGwuQDkGgTHNQbwRvDWhSbL2qaPT3kGsIL+8E+x8aX7nAEA
NMgi734B9JnwwZ/5SBct57DpFrSLOTyysEoEVfz0uCnahw7o97XNWX5tk5JrG6IlyBgCWjYHcNYcEqQJ
KHrvAqPqojgqfHBbbfCYlVCNtiNt02qxGByMtvFzIZ3d6iqGnr4BAiCqpwWAj6XRstjhgebmxM0xNlG9
ntyGU4hdENWYk25mCwC33WLI4WMZLcdHDC2G7OREqhP+o7DOainMlF0ic/Nmff969e7D42huMVAnAiMY
iQe7o0Jp2k3HNsKKClVnHco2Fubd+ymcFLLWtsrhPQr1e9CMExRQMBbO96L7Jbjmbfq2zsEi713YjUyt
gGJpkYdikEVebcZQg3dBKGPQfDjRO1FdWKqyszponwOxYC2zmT73WK6oY5Geob//ZPSdyQhACRZd+Blb
q68+98mTL87+ufF8mMFddNJfsKjKHDb39yP2YhBcqnmLtqcqRq1mE6zEzvKq0/IS9LZbLsHZHoC9i0al
OVdZDIJRgaAu6jM6yDihilIYYSWGweXUdsu3FHKHVhVCqYBEhXfODAGuQl/ZtXss+z4cezc4g5QfCdIE
kVABO6iw/37gGkGhN+7QoGUgGbRnGr9/fjWuky5SfW6gXZT+lpROTTVvRThpOx/cJ5RcDBdq8i284Do1
+i1sbPt5gEpzEbDVNNzA1+zjxrNsfe2zrLXIJ1dtO1X4WADyQmJS4rr7e7V504+GThgzpVyVSBC2mm9+
eD1ClWDci8MIbrLsRCQneV2T1clk7SzXtHOR4RMCq1EYrtMkLvFiX83seyib1YGddCaHD9LDC+h7Whho
hYlJd398kH4JvzIP/+nPaa8LnMP/5+0d8K+IxIMW7l7dDTYdUKVWPh7XvUKQk4xT0PRe6YKv4bf0nNpr
wiVoTm7WMQhj3B7V+rxSVD/1OWeJPvSXVojmBjMJ+VZiPiq/hB+MmVjZBmc5VeeCnmPZbgLfPkvm5S4u
ipxdHzUnsrwcOBebrjLWlWSVDptRpl3akMPDbOYrHVD2F8VbW7po1QgJKZEoT/y5/T/UcJgmibtiaMm7
/91NpyCxtt0T4sRnxvIQYWQy4FZ/vh3lut9ces8hjKi+wtfmu+FraJJ/ia+sFUGLcmBjZOL4Wps9ItPq
7wAAAP//+AHxxtoNAAA=
`,
	},

	"/manifests/maximum_php.yml": {
		name:    "maximum_php.yml",
		local:   "manifests/maximum_php.yml",
		size:    3546,
		modtime: 1543468996,
		compressed: `
H4sIAAAAAAAC/+xWTYvcOBO++1cUk0v6pbszPYTw4tuyH2wgsJBJ2MOyGFmqtpWWJa2q5E7n1y+y3bb7
azYZ9pDDMjC06imVyk89VdJqtcpI1tiIHNr79SbL0LaFFQ3msIvWRJsFJBeDxKIKLvoBe/nyinmxyIyT
grWzyeP4e7HIMi0E5SC+xIDwArjWBFJYKHGwuQDkGgTHNQbwRvDWhSbL2qaPT3kGsIL+8E+x8aX7nAEA
NMgi734B9JnwwZ/5SBct57DpFrSLOTyysEoEVfz0uCnahw7o97XNWX5tk5JrG6IlyBgCWjYHcNYcEqQJ
KHrvAqPqojgqfHBbbfCYlVCNtiNt02qxGByMtvFzIZ3d6iqGnr4BAiCqpwWAj6XRstjhgebmxM0xNlG9
ntyGU4hdENWYk25mCwC33WLI4WMZLcdHDC2G7OREqhP+o7DOainMlF0ic/Nmff969e7D42huMVAnAiMY
iQe7o0Jp2k3HNsKKClVnHco2Fubd+ymcFLLWtsrhPQr1e9CMExRQMBbO96L7Jbjmbfq2zsEi713YjUyt
gGJpkYdikEVebcZQg3dBKGPQfDjRO1FdWKqyszponwOxYC2zmT73WK6oY5Geob//ZPSdyQhACRZd+Blb
q68+98mTL87+ufF8mMFddNJfsKjKHDb39yP2YhBcqnmLtqcqRq1mE6zEzvKq0/IS9LZbLsHZHoC9i0al
OVdZDIJRgaAu6jM6yDihilIYYSWGweXUdsu3FHKHVhVCqYBEhXfODAGuQl/ZtXss+z4cezc4g5QfCdIE
kVABO6iw/37gGkGhN+7QoGUgGbRnGr9/fjWuky5SfW6gXZT+lpROTTVvRThpOx/cJ5RcDBdq8i284Do1
+i1sbPt5gEpzEbDVNNzA1+zjxrNsfe2zrLXIJ1dtO1X4WADyQmJS4rr7e7V504+GThgzpVyVSBC2mm9+
eD1ClWDci8MIbrLsRCQneV2T1clk7SzXtHOR4RMCq1EYrtMkLvFiX83seyib1YGddCaHD9LDC+h7Whho
hYlJd398kH4JvzIP/+nPaa8LnMP/5+0d8K+IxIMW7l7dDTYdUKVWPh7XvUKQk4xT0PRe6YKv4bf0nNpr
wiVoTm7WMQhj3B7V+rxSVD/1OWeJPvSXVojmBjMJ+VZiPiq/hB+MmVjZBmc5VeeCnmPZbgLfPkvm5S4u
ipxdHzUnsrwcOBebrjLWlWSVDptRpl3akMPDbOYrHVD2F8VbW7po1QgJKZEoT/y5/T/UcJgmibtiaMm7
/91NpyCxtt0T4sRnxvIQYWQy4FZ/vh3lut9ces8hjKi+wtfmu+FraJJ/ia+sFUGLcmBjZOL4Wps9ItPq
7wAAAP//+AHxxtoNAAA=
`,
	},

	"/manifests/medium_php.yml": {
		name:    "medium_php.yml",
		local:   "manifests/medium_php.yml",
		size:    3546,
		modtime: 1543468996,
		compressed: `
H4sIAAAAAAAC/+xWTYvcOBO++1cUk0v6pbszPYTw4tuyH2wgsJBJ2MOyGFmqtpWWJa2q5E7n1y+y3bb7
azYZ9pDDMjC06imVyk89VdJqtcpI1tiIHNr79SbL0LaFFQ3msIvWRJsFJBeDxKIKLvoBe/nyinmxyIyT
grWzyeP4e7HIMi0E5SC+xIDwArjWBFJYKHGwuQDkGgTHNQbwRvDWhSbL2qaPT3kGsIL+8E+x8aX7nAEA
NMgi734B9JnwwZ/5SBct57DpFrSLOTyysEoEVfz0uCnahw7o97XNWX5tk5JrG6IlyBgCWjYHcNYcEqQJ
KHrvAqPqojgqfHBbbfCYlVCNtiNt02qxGByMtvFzIZ3d6iqGnr4BAiCqpwWAj6XRstjhgebmxM0xNlG9
ntyGU4hdENWYk25mCwC33WLI4WMZLcdHDC2G7OREqhP+o7DOainMlF0ic/Nmff969e7D42huMVAnAiMY
iQe7o0Jp2k3HNsKKClVnHco2Fubd+ymcFLLWtsrhPQr1e9CMExRQMBbO96L7Jbjmbfq2zsEi713YjUyt
gGJpkYdikEVebcZQg3dBKGPQfDjRO1FdWKqyszponwOxYC2zmT73WK6oY5Geob//ZPSdyQhACRZd+Blb
q68+98mTL87+ufF8mMFddNJfsKjKHDb39yP2YhBcqnmLtqcqRq1mE6zEzvKq0/IS9LZbLsHZHoC9i0al
OVdZDIJRgaAu6jM6yDihilIYYSWGweXUdsu3FHKHVhVCqYBEhXfODAGuQl/ZtXss+z4cezc4g5QfCdIE
kVABO6iw/37gGkGhN+7QoGUgGbRnGr9/fjWuky5SfW6gXZT+lpROTTVvRThpOx/cJ5RcDBdq8i284Do1
+i1sbPt5gEpzEbDVNNzA1+zjxrNsfe2zrLXIJ1dtO1X4WADyQmJS4rr7e7V504+GThgzpVyVSBC2mm9+
eD1ClWDci8MIbrLsRCQneV2T1clk7SzXtHOR4RMCq1EYrtMkLvFiX83seyib1YGddCaHD9LDC+h7Whho
hYlJd398kH4JvzIP/+nPaa8LnMP/5+0d8K+IxIMW7l7dDTYdUKVWPh7XvUKQk4xT0PRe6YKv4bf0nNpr
wiVoTm7WMQhj3B7V+rxSVD/1OWeJPvSXVojmBjMJ+VZiPiq/hB+MmVjZBmc5VeeCnmPZbgLfPkvm5S4u
ipxdHzUnsrwcOBebrjLWlWSVDptRpl3akMPDbOYrHVD2F8VbW7po1QgJKZEoT/y5/T/UcJgmibtiaMm7
/91NpyCxtt0T4sRnxvIQYWQy4FZ/vh3lut9ces8hjKi+wtfmu+FraJJ/ia+sFUGLcmBjZOL4Wps9ItPq
7wAAAP//+AHxxtoNAAA=
`,
	},

	"/manifests/small_jmeter.yml": {
		name:    "small_jmeter.yml",
		local:   "manifests/small_jmeter.yml",
		size:    3116,
		modtime: 1543468996,
		compressed: `
H4sIAAAAAAAC/+xWTY/bNhC981cM0kPiotpaxm6A6Fb0AwiQUzZFj8SYGkvsUqTAIbXr/PqCkqwPr9cN
gh6CIvBF5Bu9Gb95HCrLMsGqpgYL6LY3uRBkO2mxoQIeojXRCk/solckK+9iO2Jv3lzY3myEcQqDdjZF
nJ43GyE0IheAn6Mn+AFCrRkUWtjTuOc8sGsIXKjJQ2swHJxvhOiagZ8LAZDBkPzv2LR79yQAABoKWPRP
AEMl4diexSgXbSgg7xf8EAu4D2hL9KX87T6X3a4Hhve65qy+rknFdQ3zT6Ci92SDOYKz5pggzcCxbZ0P
VPYsjmXr3UEbOlWFZaPtJNu82mzGAKNtfJLK2YOuoh/kGyEA5npeALRxb7SSD3Tk5XbS5sTNXN/MYWMW
Ds5jNdWkm8UCwB0O5Av4cx9tiPfkO/JilZHrhP+K1lmt0MzVJTHztzfb2+zDp/tpuyPPvQkMBuIw7juW
peaHOW2DFisq+92xbVNjPnyc6RSqWtuqgI+E5V9eB5ohTxhIunYw3R/eNe/Tf+sDLIVH5x8mpTLguLcU
xmawpZDlE9UYLZlU9DocV35nrqXlSpz1QbcFcMCglVj6s6FAPkts5PkrLPjdSd+YkwBKDNjTL9TKvjjv
1czPcv/etOG4gHt21p9JVvsCbrdfbO6FZP/i78GyyeIAL5t8gLwztEi7vCxukkyp3MvokGVuLvqV98Yi
jMNSptIlWdwbKpPbX8Im718kaFxJBbxmbStD0rqSXl8LD7UnLGWblOjfzLfba/HGuVaOR3t3dy3SY9PK
2CZq7coCdkKIzlJY3WvdPJCwLD0xS25R9XXc9L+f87fDIexb/awJZxPNo62WL+9uJ6jCQI94nMD8EtPK
Pkuy3d3dNboE5ydIiF6FPRq0ilLDxWUnrqRYzttn4T5eMCAa4x4z5nq2r9cuxa/bWGpPajhn7+3eRVtO
ECpFzAX8kqgWNC445UwBn1Q7z6vh4yfd/HKU5tWPr+YsxEHbfgKvYna7c4ZTp1tPB/30MsvluPWV87WS
ZSV1l2XL/6e6PZfhbDatVNh9Iyrk23fv/ksdRIdepzG6OnvT5b/4JkmrfwIAAP//AsmWwiwMAAA=
`,
	},

	"/manifests/small_kubernetes.yml": {
		name:    "small_kubernetes.yml",
		local:   "manifests/small_kubernetes.yml",
		size:    3632,
		modtime: 1543468996,
		compressed: `
H4sIAAAAAAAC/+xWz6vbOBC++68YXi7NkqRJKKX4tuwPtlBY6GvZw7IYWZ7YamTJqxk5Tf/6RbZiO4lf
ty176GF58IjmG83I33ya0Xq9TkhWWIsU2u1mlyRo2syIGlM4eqO9SRyS9U5iVjrrm4g9ezZjXi4TbaVg
ZU3wuPxeLpNECUEpiE/eISyAK0UghYEco806IFsjWK7QQaMFH6yrk6St+/iUJgBr6JN/8HWT248JAECN
LNLuF0B/Ej43Nz7SesMp7LoFHX0KjyxMIVyR/fy4y9p9B/T72vrmfG0dDtfWRCuQ3jk0rM9gjT4HSBGQ
bxrrGIsuiqWscfagNF5OJYpamYG2cbVcRgetjP+YSWsOqvSupy9CAETVuABofK6VzI54pqk5cHOJTVRt
RreYhdg6UQ5nUvVkAWAPB3QpvM+9Yf+IrkWXXGWkKuA/CWONkkKPpwtk7l5uti/Wb949DuYWHXUi0IKR
ONotZYWi45i2FkaUWHTWWLahMG/ejuGkkJUyZQpvURR/OMU4Qg4FY2abXnS/Olu/Dt/WORjkk3XHgak1
kM8NciwGGeT1bggVvTNC6Z3i85XeiarMUJnc1EE1KRALVjKZ6PPoc3QGGenf5be/k9//MvrOZARQCBZd
+Alb6y/O+9nMd7l/qRs+T+AuOqlPmJV5CrvtdsAWUXCh5i2anirvVTHpYDl2luedllegDt1yBdb0AJys
10Xoc6VBJxgLENRF/YYbtABtRZHlQgsj0UWna9vT3rmQRzRFJorCIVHWWKtjiFnoC2/ueBmHC+ysRkov
LCkCT1gAWyixJwG4Qiiw0fZco2Eg6VTDNJAwnY+bII5QpHn0pheMVRv3d3n6YSptgYMfQCvcQP2iv0bO
fkDJWZy9wT9rBFehJzyFDR3iOkSpOHPYKorjes4+2Xpz6qZqkqQ1yFeTuR0FcakVNUJiEO6m+3u+e9l3
kk5HE2HNKsoJU043718MUCkYT+I8gLskudJTF3o89r0KF7fdONrmxBaDTU/6pCaDW4VCcxVaeI4zeyvm
pgcHqKsLW2l1Cu9kAwvoG4LQ0Artg17/fCebFfzGHP/TX9Pd1nEKr7YT0wIc/u2ROCrk4flDtCmHRegF
l5TdMwY5XIEQODx4ugQb+D28x06KcAWKg5uxDEJre8Jic/ddYUp+9rPuDrzfR5Pz+kmmAvb1RL0vmhX8
qPWUpYOzhkPVZui6FPQz0Ne0psveqRSyu/In873r6lLNdLC7XQN9U/K6Oq1DtnEMO2XDhhT2k0lSKIey
Hz+vTW69KQZISIlEaSDSniZhrosax3jfeAKBWby5Dz88jFmQWJnuYXLl82p7G2Eg0+FBfXw6yrzfVI3f
QhhRNcPX7rvha7//L/lKWuGUyCMbAxOXN+DkbRpW/wQAAP//ShzyYjAOAAA=
`,
	},

	"/manifests/small_php.yml": {
		name:    "small_php.yml",
		local:   "manifests/small_php.yml",
		size:    5269,
		modtime: 1543468996,
		compressed: `
H4sIAAAAAAAC/+xXS4vcOBC++1cUk0Myy3RnuknCxrd9soHAQiZhD8tiZKnaVkaWtCrJnc6vXyS7/ehX
kiGHsISBoVVVqip99fRisciI19iwHNrb5SrLULeFZg3mcB+0CjpzSCY4jkXlTLA978mTE+Tr60wZzrw0
Okrsf19fZ5lkjHJgH4NDeAS+lgScaSixpxkHZBoE42t0YBXzG+OaLGubTj/lGcACOuPvQ2NL8yEDAGjQ
szz9Aug88Tt7IMNN0D6HVTrQfcjhzjMtmBPFr3erol0nRnevbQ78a5voXNsQ3QAPzqH2agdGq11kSQIK
1hrnUSQthgrrzEYq3HvFRCP1ANt4ur7uBZTU4UPBjd7IKrgOvp4FQFSPBwAbSiV5cY87mpIjNnvdRPVy
FOutkDeOVYNPspkcAMxmgy6Hd2XQPtyha9FlM4tUR/4vTBstOVOjdxHM1Yvl7bPF67d3A7lFRykJFPNI
vqcbKoSk+9FswzSrUCRqH7YhMK/fjOo447XUVQ5vkIm/nPQ4shwyj4WxXdL97kzzKr4tCWj0W+PuB6QW
QKHU6PtgkEa/WA2qeumCkAcn/W6W70R1oanKDuIgbQ7kmZc8m+TnFssFJRTpIfn3PY++sTwCEMyzpH6C
1uKz7V60fGT7t8b63YSdtJP8iEVV5rC6vR14j/qMizFvUXdQhSDFpIWVmChPUzLfgNyk4w0Y3TFga4IS
sdFVGh3zKIBR0vqAElKGiaJkimmOrheZ087JlozfoxYFE8IhUWGNUb2Ck6zPLNstll0hDsXrjELK9wBJ
gkAowBuosHs/+BpBoFVm16D2QNxJ62l4/3Q2LmNexPic4SYt3ZjkRowxb5mblZ115j1yX/QTNcoWlvk6
Fvo53lD2UwWV9IXDVlI/gk/Rh4sH3traTpvY+wY9ukXEtq/iC23s5xXNetj3Fva9hZ1tYc9uP7u1TCD7
RKV36fqJGT02gIeUc2fibBH3HqS+Fv0uULNSoYipfo43K+IjocYIzOExSV0pLLQR+PiSuK8dMlHYCEO6
OZ0VJ+SVMbboi3r9/JKkY40tgo2qpRE5rLOs1ehnS3k7joJ9pybLeHJjmf6erl50BZjCfBSDg1nimK6m
l9fPBlbFPG7ZbmCuTmmapc5U2fr580vqInuVZbPxNHvoqYE264aJcmpqHT35wmirkSlfxwZaHqdr7b3t
WNlkAnjDjcrhLbfwCLpSZApapkKceH+/5fYG/vC+/0//jHeN8zn8OF0sHP4bYuS7KXT19KqnSYciLhF7
c+kDCH0coFFp/FRKypfwZ/yS20rCG5A+imnjgSlltiiWhwGj+tJzDhxdd/uyC+oMMpHzpcC8E/YGflJq
RGXjjPYxOkfw7MN2lvHlW8w03MVRkLPTrW+WlserztGlk4ilkCyisQlk0sQLOawnHURIh7zr7690aYIW
A4txjkR5xM9sPxHDfo+J2BV9WV79cDVaQfJSp8k/k5mg3GsYkHS4kR/OazktN029hwBGVJ/Aa/XN4NUX
yVfH62DOfiFkC4HtadhW/1PcjmE4WCNmKKy/ERRWty9ffk0cspY5GTeeWcsalvTJt0M8/RcAAP//JPyq
lZUUAAA=
`,
	},

	"/manifests/small_tomcat.yml": {
		name:    "small_tomcat.yml",
		local:   "manifests/small_tomcat.yml",
		size:    3695,
		modtime: 1543468996,
		compressed: `
H4sIAAAAAAAC/+xWT4vjuBO9+1MU3ZfJjyTdaYbhh2/L/mEHBhame9jDshhZqtiayJJXVXI68+kX2Y7t
JE7vTLOHOSwNTVSvVFV+9VTSarVKSJZYiRSa+/UmSdA2mRUVprAL1gSbeCQXvMSs8C7UPfbmzYx5sUiM
k4K1s9Hj+HuxSBItBKUgvgSPcAtcagIpLOTY25wHchWC4xI91Ebw1vkqSZqqi09pArCCLvnnUNW5e04A
ACpkkba/ALpK+FCf+UgXLKewaRe0Cyk8srBKeJX99LjJmocW6PY11Vl9TRWLayqiJcjgPVo2B3DWHCKk
CSjUtfOMqo3iKKu922qDx6qEqrQdaBtXi0XvYLQNz5l0dquL4Dv6egiAqBwXAHXIjZbZDg80NUdujrGJ
yvXo1mchdl4UQ026miwA3HaLPoVPebAcHtE36JOTjFRG/EdhndVSmLG6SObm3fr+7erD0+NgbtBTKwIj
GIl7u6NMadqNaSthRYGqtfZtGxrz4eMYTgpZaluk8BGF+t1rxhHyKBgzV3ei+8W76n38ttbBIu+d3w1M
rYBCbpH7ZpBFXm2GUL13RiiD13w40TtRmVkqkrM+6DoFYsFaJhN97jFfUcsivUZ//+noO9MRgBIs2vAT
tlZfnffFzBe5f65qPkzgNjrpL5gVeQqb+/sBu+0VF3veoO2oCkGryQjLsbXctWJegt62yyU42wGwd8Go
OOgKi14wKhDURn3FETJOqCwXRliJvnc5tV3zzYXcoVWZUMojUVY7Z/oAs9BXHts95t1BHA6vdwYpPRKk
CQKhAnZQYPf9wCWCwtq4Q4WWgaTXNdPw/dO7cR11EftzBW2jdNekdGrseSP8ybGrvfuMkrP+Ro2+WS24
jAf9GjYc+2mAQnPmsdHUX8Fz9mHjWbXsKin4ao2dV9Z5Zd2IqAXR3nkVU72ExxdAY5FPbvFm1M6xtVQL
iVHj6/bvbvOuGzqt5CYanBWfF7aYbn54O0CFYNyLwwBukuREfid1zQn2ZGi3ljlVXlT4gnRLFIbLOONz
vNhXMtcdlEw6zE46k8KTrOEWumkhDDTChKjoP55kvYRfmfv/9Oe413lO4f/TweHxr4DEvcpu7m56m/ao
4pA4pmsfOMjxgMSg8SnUBl/Db/GltteES9Ac3axjEMa4Par1eaeofOlzzgp96O5DH8wVZiLyrcR8UvUS
fjBmZGXrneXYnQt6jm27Cnz7lJq2O7tocjI/xE5keTnKLjbNMta2ZBWTTSjTLm5I4WFymyjtUXZX0Hub
u2DVAAkpkSiN/Ln9P/Swn1ORu6w/kjf/uxmzILG27ePkxGfCch9hYNLjVj9fjzLvN5XeawgjKmf42nw3
fPWH5F/iK2mE1yLv2RiYOL4DJ+/TbnV6dcwP/cmmwfR3AAAA//9Tq/GNbw4AAA==
`,
	},

	"/manifests/small_wildfly.yml": {
		name:    "small_wildfly.yml",
		local:   "manifests/small_wildfly.yml",
		size:    3551,
		modtime: 1543468996,
		compressed: `
H4sIAAAAAAAC/+xWTYvcOBO++1cUk0v6pbszPYTw4tuyH2wgsJBJ2MOyGFmqtpWWJa+q5E7n1y+y1bb7
azYZ9pDDMjC06imVyk89VdJqtcpI1tiIHLr79SbL0HaFFQ3msAvWBJt5JBe8xKLyLrQJe/nyinmxyIyT
grWz0eP4e7HIMi0E5SC+BI/wArjWBFJYKDHZnAdyDYLjGj20RvDW+SbLumaIT3kGsILh8E+haUv3OQMA
aJBF3v8CGDLhQ3vmI12wnMOmX9Au5PDIwirhVfHT46boHnpg2Nc1Z/l1TUyua4iWIIP3aNkcwFlziJAm
oNC2zjOqPoqjovVuqw0esxKq0XakbVotFsnBaBs+F9LZra6CH+hLEABRPS0A2lAaLYsdHmhujtwcYxPV
68ktnULsvKjGnHQzWwC47RZ9Dh/LYDk8ou/QZycnUh3xH4V1VkthpuwimZs36/vXq3cfHkdzh556ERjB
SJzsjgqlaTcd2wgrKlS9NZVtLMy791M4KWStbZXDexTqd68ZJ8ijYCxcO4juF++at/HbegeLvHd+NzK1
AgqlRU7FIIu82oyhkndBKIPXfDjRO1FdWKqyszroNgdiwVpmM33usVxRzyI9R3//6eg70xGAEiz68DO2
Vl997pMnX5z9c9PyYQb30Ul/waIqc9jc34/Yi6S4WPMO7UBVCFrNRliJveVVL+Yl6G2/XIKzAwB7F4yK
g66y6AWjAkF91Ge0kHFCFaUwwkr0yeXUdsu3FHKHVhVCKY9EReucSQGuQl/Ztnssh0Ycm9c7g5QfCdIE
gVABO6hw+H7gGkFha9yhQctA0uuWafz++d24jrqI9bmB9lGGa1I6NdW8E/6k7VrvPqHkIt2o0bdoBdex
0W9hY9vPA1SaC4+dpnQFX7OPG8+y3WujtuaQZZ1FPrlvu6nKxyJQKyRGNa77v1ebN8N46MUxU8tVmXhh
q/nmh9cjVAnGvTiM4CbLToRyktc1aZ2M195yTT8XGT4hshqF4TpO4xIv9tXM7QBls1qwk87k8EG28AKG
vhYGOmFC1N4fH2S7hF+Z03/6c9rrPOfw/3mLe/wrIHHSw92ru2TTHlVs5+Nx/VMEOUo5Bo2Plj74Gn6L
b6q9JlyC5uhmHYMwxu1Rrc8rRfVTn3OW6MNwc/lgbjATkW8l5qNql/CDMRMrW+8sx+pc0HMs203g2+fJ
vNzFRZGz6+PmRJaXQ+di01XG+pKs4mEzyrSLG3J4mM19pT3K4bJ4a0sXrBohISUS5ZE/t/+HGqaJErkr
Ukve/e9uOgWJte2fESc+M5ZThJFJj1v9+XaU635z6T2HMKL6Cl+b74av1CT/El9ZJ7wWZWJjZOL4Ypu9
JOPq7wAAAP//boP/xN8NAAA=
`,
	},

	"/manifests": {
		name:  "manifests",
		local: `manifests`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"manifests": {
		_escData["/manifests/large_php.yml"],
		_escData["/manifests/maximum_php.yml"],
		_escData["/manifests/medium_php.yml"],
		_escData["/manifests/small_jmeter.yml"],
		_escData["/manifests/small_kubernetes.yml"],
		_escData["/manifests/small_php.yml"],
		_escData["/manifests/small_tomcat.yml"],
		_escData["/manifests/small_wildfly.yml"],
	},
}
