- name: php
  questions:
    - var_name: "concurrent_user"
      type: int
      description: "The concurrent user"
  transitions:
    - name: small_php
      condition: "concurrent_user <= 100"
    - name: medium_php
      condition: "concurrent_user > 100 && concurrent_user <= 1000"
    - name: large_php
      condition: "concurrent_user > 1000 && concurrent_user <= 2000"
    - name: maximum_php
      condition: "concurrent_user > 2000"

- name: small_php
  questions:
    - var_name: "final_artifact"
      persistent: true
      description: "Guess your final artifact is:"
      default: "small_php.yml"

- name: medium_php
  questions:
    - var_name: "final_artifact"
      persistent: true
      description: "Guess your final artifact is:"
      default: "medium_php.yml"

- name: large_php
  questions:
    - var_name: "final_artifact"
      persistent: true
      description: "Guess your final artifact is:"
      default: "large_php.yml"

- name: maximum_php
  questions:
    - var_name: "final_artifact"
      persistent: true
      description: "Guess your final artifact is:"
      default: "maximum_php.yml"
  