---
- import_role:
    name: nginxinc.nginx
  become: true
  become_user: root

- import_role:
    name: geerlingguy.java
  become: true
  become_user: root

- name: Installing repo for Java 8 in Ubuntu
  apt_repository: repo='ppa:openjdk-r/ppa'
  become: true
  become_user: root  

- import_role:
    name: geerlingguy.jenkins
  become: true
  become_user: root
  vars:
    jenkins_admin_username: "{{kunlun_jenkins_admin_username}}"
    jenkins_admin_password: "{{kunlun_jenkins_admin_password}}"

- name: Setup directories
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    # group: "{{ dashboard_group }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ project_log_root }}"
  become: true
  become_user: root

# remove the default nginx site
- name: Remove the default configuration
  file:
    path: "{{ nginx_config_root }}/conf.d/default.conf"
    state: absent
  become: true
  become_user: root

# setup the nginx config.
- name: Update nginx config
  template:
    src: nginx.j2
    dest: "{{ nginx_config_root }}/conf.d/{{ kl_site_name }}.conf"
    owner: "{{ ansible_user }}"
    mode: 0644
  become: true
  become_user: root

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: true
  become_user: root
